tests:
- changed-files:
  - any-glob-to-any-file:
    - tests/**/*

CI:
- changed-files:
  - any-glob-to-any-file:
    - .github/**/*

code style:
- changed-files:
  - any-glob-to-any-file:
    - .editorconfig

documentation:
- changed-files:
  - any-glob-to-any-file:
    - README.md
