version: "3.2"

services:
  integration-test:
    container_name: serilog.sinks.rabbitmq.tests.integration
    build:
      context: ./ 
      dockerfile: docker/integration-test/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    container_name: serilog.sinks.rabbitmq.server
    image: rabbitmq:3.12.12-management
    healthcheck:
      test: rabbitmqctl status || exit 1
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 25672:25672
      - 15671:15671
      - 15672:15672
    volumes:
      - ./docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./docker/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.conf:ro
      - ./docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
      - ./docker/rabbitmq/ca-cert.pem:/etc/ssl/ca-cert.pem:ro
      - ./docker/rabbitmq/server-cert.pem:/etc/ssl/server-crt.pem:ro
      - ./docker/rabbitmq/server-key.pem:/etc/ssl/server-key.pem:ro
