version: '3'

services:
  consoleapp:
    container_name: serilog.sinks.rabbitmq.tests.console
    build:
      context: ./ 
      dockerfile: docker/consoleapp/Dockerfile
    depends_on: 
      - rabbitmq
  rabbitmq:
    container_name: serilog.sinks.rabbitmq.server
    build:
      context: ./
      dockerfile: docker/rabbitmq/Dockerfile
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 25672:25672
      - 15671:15671
      - 15672:15672